define({
    blog: "部落格",
    blogList: "部落格列表",
    singleEdit: "新建",
    singleView: "查看",
    setting: "设定",
    titleEmpty: "標題不能為空！",
    "delete": "删除",
    comment: "評論",
    read: "閱讀",
    deleteConfirm: "確定删除此部落格?",
    tags: "標籤:",
    viweOrigin: "查看原始路径",
    saveSuccessful: "保存成功!",
    cancelConfirm: "確定要取消嗎?",
    selectFirst: "首先先选择一篇博客",
    leaveConfirm: "確定离开此页面？\n必须保存所有內容.",
    changeEditor: "更换编辑模式",
    deleteSuccessful: "成功删除!",
    enterTag: " 回車添加標籤",
    prev: "上一步",
    next: "下一步",
    viewSetting: "视图設定",
    title: "標題",
    towards: "指向  ",
    comments: "評論",
    sharedWith: "分享至 ",
    markdown: "Markdown",
    writtenBy: "作者",
    origin: "原文",
    back: "返回",

    list: "列表",
    add: "添加",
    normalEdit: "正常编辑",
    translate: "翻譯",
    edit: "編輯",
    preview: "預覽",
    setting: "設定",
    written: "編輯日期",
    fontFamily:"字體樣式",
       fontSize:"字體大小",
       dataX:"橫向展示設置",
       dataY:"縱向展示設置",
       dataZ:"深向展示設置",
       dataScale:"縮放展示設置",
       dataRotate:"旋轉展示設置",
       dataRotateX:"橫向旋轉展示設置",
       dataRotateY:"縱向旋轉展示設置",
       dataRotateZ:"深向旋轉展示設置"
})
