define({
    root: ({
        blog: "博客",
        blogList: "博客列表",
        singleEdit: "新建",
        singleView: "查看",
        setting: "设置",
        titleEmpty: "标题不能为空!",
        "delete": "删除",
        comment: "评论",
        read: "阅读",
        deleteConfirm: "确定删除此博客?",
        tags: "标签:",
        viweOrigin: "查看原始路径",
        saveSuccessful: "保存成功!",
        cancelConfirm: "确定取消?",
        selectFirst: "请先选择一篇博客",
        leaveConfirm: "定离开此页面？\n必须保存所有內容",
        changeEditor: "切换编辑模式",
        deleteSuccessful: "删除成功!",
        enterTag: " 回车添加标签",
        prev: "上一步",
        next: "下一步",
        viewSetting: "视图设置",
        title: "标题",
        towards: "指向  ",
        comments: "评论",
        sharedWith: "分享至 ",
        markdown: "Markdown",
        writtenBy: "作者",
        origin: "原文",
        back: "返回",

        list: "列表",
        add: "添加",
        normalEdit: "正常编辑",
        translate: "翻译",
        edit: "编辑",
        preview: "预览",
        setting: "设置",
        written: "编辑日期",
        fontFamily: "字体样式",
        fontSize: "字体大小",
        dataX: "横向展示设置",
        dataY: "纵向展示设置",
        dataZ: "深向展示设置",
        dataScale: "缩放展示设置",
        dataRotate: "旋转展示设置",
        dataRotateX: "横向旋转展示设置",
        dataRotateY: "纵向旋转展示设置",
        dataRotateZ: "深向旋转展示设置",
        slide: "幻灯片",
        yourPostTitle: "请输入标题",

        publicStatus: "公开",
        privateStatus: "私有"
    }),
    "en": true,
    "zh": true,
    "zh-tw": true,
    "ja": true
});
