define({
    blog: "Blog",
    blogList: "Blog List",
    singleEdit: "New",
    singleView: "View",
    setting: "Setting",
    titleEmpty: "Title can't be empty!",
    comment: "Comment",
    read: "Read",
    deleteConfirm: "Are you sure to delete this blog?",
    tags: "Tags:",
    viweOrigin: "View the origin url",
    saveSuccessful: "Save sucessfully!",
    cancelConfirm: "Do you really want to cancel?",
    selectFirst: "Select a blog first",
    changeEditor: "Change Editor",
    deleteSuccessful: "Delete Successful!",
    enterTag: " Enter a Tag Name",
    prev: "<< Prev",
    next: "Next >>",
    translate: "Translate",
    edit: "Edit",
    "delete": "Delete",
    preview: "Preview",
    title: "Title",
    towards: "Towards  ",
    comments: " Add commentary",
    sharedWith: "I've write a post: ",

    markdown: "Markdown",
    writtenBy: "Written By",
    origin: "Origin",
    back: "Back",

    list: "List",
    add: "Add",
    normalEdit: "NormalEdit",
    translate: "Translate",
    edit: "Edit",
    preview: "Preview",
    setting: "Setting",
    written:" Written",
     fontFamily:"Font Family",
       fontSize:"Font Size",
       dataX:"Data-X",
       dataY:"Data-Y",
       dataZ:"Data-Z",
       dataScale:"Data-Scale",
       dataRotate:"Data-Rotate",
       dataRotateX:"Data-Rotate-X",
       dataRotateY:"Data-Rotate-Y",
       dataRotateZ:"Data-Rotate-Z"
});